### ISSUE TITLE
issue: daily transaction limit error

### ISSUE THREAD

**Issue by joshkimmell** [watson-developer-cloud/business-intelligence-application-starter-kit#26]
Unable to retrieve answers from Watson. 
```
 Status: 400, Message: {
  "code": 400,
  "error": "daily-transaction-limit-exceeded"
}
```
Using Chrome Version 49.0.2623.87 (64-bit) on Mac

**Comment by germanattanasio** [comment]
This is a limitation in the Alchemy key we are using.

**Comment by jzhang300** [comment]
@joshkimmell You need a high transaction Alchemy key

**Comment by germanattanasio** [comment]
there is nothing we can do for this
