### ISSUE TITLE
Unable to retrieve answers from Watson. 

### ISSUE THREAD

**Issue by lionelmace** [watson-developer-cloud/business-intelligence-application-starter-kit#29]
I just deployed the starter kit successfully. When submitting the company name in the first page, I gest the following errors:

Unable to retrieve answers from Watson. 
```
 Status: 400, Message: {
  "code": 400,
  "error": "invalid-permissions-for-call"
}
```

**Comment by ramakay** [comment]
I get the same issue, any suggestions>
