### ISSUE TITLE
Deploy on Bluemix button needs testing

### ISSUE THREAD

**Issue by chanskw** [watson-developer-cloud/business-intelligence-application-starter-kit#3]
We have a deploy on bluemix button.
Not sure if this works, please test @abtinf.

**Comment by germanattanasio** [comment]
The deploy to bluemix will work but the user needs to specify the `ALCHEMY_API_KEY` manually

**Comment by jzhang300** [comment]
The Deploy to Bluemix works, though people would need to provide their own ALCHEMY_API_KEY, which is specified in readme.
