### ISSUE TITLE
Application sometimes fail to load articles

### ISSUE THREAD

**Issue by chanskw** [watson-developer-cloud/business-intelligence-application-starter-kit#6]
Very intermittent problem, sometimes when clicking on the top sources, the application cannot load articles.  Need to determine why.

**Comment by germanattanasio** [comment]
do you have the name of the api call that is failing ?

**Comment by chanskw** [comment]
Possible error... not always this case...

TypeError: undefined is not an object (evaluating 'rowData.tone.children.forEach')
column: 34
line: 65
message: "undefined is not an object (evaluating 'rowData.tone.children.forEach')"
sourceURL: "http://localhost:6001/js/app/articleTable.js"
stack: "http://localhost:6001/js/app/articleTable.js:65:34↵forEach@[native code]↵http://localhost:6001/js/app/articleTable.js:45:45↵http://localhost:6001/js/d3.min.js:3:15120↵Y@http://localhost:6001/js/d3.min.js:1:4464↵each@http://localhost:6001/js/d3.min.js:3:15092↵_addRows@http://localhost:6001/js/app/articleTable.js:43:13↵createTable@http://localhost:6001/js/app/articleTable.js:120:18↵_setup@http://localhost:6001/js/app/articleTable.js:32:21↵ArticleTable@http://localhost:6001/js/app/articleTable.js:11:16↵http://localhost:6001/js/app/mainController.js:272:54↵[native code]↵promiseReactionJob@[native code]"

**Comment by germanattanasio** [comment]
v3 is a different API so the response is completely different and it's large comparing to v2

API Explorer: https://watson-api-explorer.mybluemix.net/apis/tone-analyzer-v3-beta

**Comment by chanskw** [comment]
Thanks... is there a migration guide somewhere?

**Comment by germanattanasio** [comment]
no :(

**Comment by chanskw** [comment]
Ok... will see what we can do tomorrow...
The timing of this is just bad.  But if there is something simple, we can try to migrate.  Thanks for the heads up.

**Comment by germanattanasio** [comment]
I added a commit(fcd0ede234f0369cf71db605480c1e1634fefb07) that detects this problem and returns:
```
{
  code: 404,
  error: 'Article not found'
}
```

Now we need to update the UI to use that information to alert users.

**Comment by chanskw** [comment]
Fixed... This hasn't happened today. I am assuming that the new version of the API works better.  Need to keep an eye on this.
