### ISSUE TITLE
Determine memory requirement for application

### ISSUE THREAD

**Issue by chanskw** [watson-developer-cloud/business-intelligence-application-starter-kit#9]
Figure out what the minimum memory requirement is for application.
Potential tune up.

**Comment by germanattanasio** [comment]
I've enable compression in express using https://github.com/expressjs/compression.

I think that this could be related to getting the text from alchemy and calling tone analyzer. if is a large text tone will return a large json response.

**Comment by chanskw** [comment]
Tested at 512 MB on bluemix.
With 2 users, the peak memory requirement was at 150 MB.

Leaving it like this for now.
